# Generated by Django 4.2.15 on 2024-08-16 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Magazin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MagazinGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaspi.good')),
                ('magazin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaspi.magazin')),
            ],
        ),
        migrations.AddField(
            model_name='magazin',
            name='goods',
            field=models.ManyToManyField(through='kaspi.MagazinGoods', to='kaspi.good'),
        ),
        migrations.AddField(
            model_name='magazin',
            name='staff',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
