# Generated by Django 4.2.15 on 2024-08-19 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kaspi', '0003_kaspiobject_alter_magazingoods_magazin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='For_Good',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kaspi.good',),
        ),
        migrations.CreateModel(
            name='Magazin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=256)),
                ('goods', models.ManyToManyField(through='kaspi.MagazinGoods', to='kaspi.good')),
                ('staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='magazingoods',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaspi.magazin'),
        ),
        migrations.DeleteModel(
            name='kaspiObject',
        ),
    ]
