# Generated by Django 5.0.6 on 2024-08-23 12:39

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaspi', '0004_for_good_magazin_alter_magazingoods_magazin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazin',
            name='array_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='magazin',
            name='date_range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magazin',
            name='datetime_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
        ),
    ]
