# Generated by Django 5.0.6 on 2024-08-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='djangoEx')),
                ('photo', models.ImageField(upload_to='')),
                ('id_photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
